name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      BranchName:
        default: master
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.BranchName}}
          
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: cloutojp/heroku-deploy@v1.0.0  
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: ${{secrets.HEROKU_APP_NAME}}
          email: ${{secrets.HEROKU_EMAIL}}
          dockerfile_path: "."
